name: Create Tag

# Allows the workflow to be triggered manually
on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version (e.g., v1.0.0)'
        required: true
        default: '1.0.0'  # Default version (optional)

permissions:
  contents: write
  
jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Create a new tag based on the input version
      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Get the tag version from the input
          tag_version="${{ github.event.inputs.tag_version }}"

          # Create or update the tag locally
          git tag -f $tag_version

          # Force push the new tag to the repository, overwriting if it exists
          git push origin $tag_version --force

      # Trigger the Create Release workflow after the tag is created
      - name: Trigger Create Release Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'create_release.yml',  # Make sure this matches the release workflow file name
              ref: 'main',  # Specify the branch or ref where the workflow runs
              inputs: {
                tag: "$tag_version"  # Pass the tag version to the release workflow
              }
            })
