name: Create Release

on:
  push:
    tags:
      - '*'  # Triggers when any tag is pushed
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create a release for'
        required: false

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Tag
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ -z "${{ github.event.inputs.tag }}" ]; then
              echo "Error: No tag provided in workflow dispatch."
              exit 1
            fi
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${{ github.ref#refs/tags/ }}"
            echo "TAG=$TAG" >> $GITHUB_ENV
          else
            echo "Error: No tag found."
            exit 1
          fi

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
