name: Create Release

# Allows the workflow to be triggered manually
on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'  # Default version (optional)

permissions:
  contents: write
  
jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Create a new tag based on the input version
      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Get the tag version from the input
          tag_version="${{ github.event.inputs.tag_version }}"

          # Create or update the tag locally
          git tag -f $tag_version

          # Force push the new tag to the repository, overwriting if it exists
          git push origin $tag_version --force

  create_release:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Release Tag
        id: vars
        run: |
          echo "TAG=${{ github.event.inputs.tag_version }}" >> $GITHUB_ENV

      - name: Extract Release Notes from CHANGELOG.md
        id: extract_notes
        shell: bash
        run: |
          TAG_VERSION="${{ env.TAG#v }}"  # Remove 'v' prefix if present
          
          # Extract release notes for the current version
          RELEASE_NOTES=$(awk '/^## \[?'"$TAG_VERSION"'\]?/{flag=1;next}/^## /{flag=0}flag' CHANGELOG.md)
          
          if [ -z "$RELEASE_NOTES" ]; then
            echo "Error: Release notes for tag $TAG_VERSION not found in CHANGELOG.md"
            exit 1
          fi

          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
